// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeIM2Sejll_AT58Sa08f7FcR9e_3WRhyg',
    appId: '1:871591093675:web:55f5333b955602c25b5eee',
    messagingSenderId: '871591093675',
    projectId: 'binuapp-9bd91',
    authDomain: 'binuapp-9bd91.firebaseapp.com',
    storageBucket: 'binuapp-9bd91.firebasestorage.app',
    measurementId: 'G-1VMTP8CK6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8Ti5NKNItB-fCSH1RM9jsWxEFXjOFEu4',
    appId: '1:871591093675:android:6a76cd42354748e85b5eee',
    messagingSenderId: '871591093675',
    projectId: 'binuapp-9bd91',
    storageBucket: 'binuapp-9bd91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9NdB8cXOrfoMrN1Mz14xg2ys_9RcpLz0',
    appId: '1:871591093675:ios:a3229c2bba75e8a05b5eee',
    messagingSenderId: '871591093675',
    projectId: 'binuapp-9bd91',
    storageBucket: 'binuapp-9bd91.firebasestorage.app',
    iosBundleId: 'com.example.binuFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9NdB8cXOrfoMrN1Mz14xg2ys_9RcpLz0',
    appId: '1:871591093675:ios:a3229c2bba75e8a05b5eee',
    messagingSenderId: '871591093675',
    projectId: 'binuapp-9bd91',
    storageBucket: 'binuapp-9bd91.firebasestorage.app',
    iosBundleId: 'com.example.binuFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeIM2Sejll_AT58Sa08f7FcR9e_3WRhyg',
    appId: '1:871591093675:web:92f2733ec7c4867f5b5eee',
    messagingSenderId: '871591093675',
    projectId: 'binuapp-9bd91',
    authDomain: 'binuapp-9bd91.firebaseapp.com',
    storageBucket: 'binuapp-9bd91.firebasestorage.app',
    measurementId: 'G-J9F444QQFE',
  );
}
